const courts = [
    { code: "BB1B", city: "Bielsko-Biała" },
    { code: "BB1C", city: "Cieszyn" },
    { code: "BB1Z", city: "Żywiec" },
    { code: "BI1B", city: "Białystok" },
    { code: "BI1P", city: "Bielsk Podlaski" },
    { code: "BI1S", city: "Sokółka" },
    { code: "BI2P", city: "Hajnówka" },
    { code: "BI3P", city: "Siemiatycze" },
    { code: "BY1B", city: "Bydgoszcz" },
    { code: "BY1I", city: "Inowrocław" },
    { code: "BY1M", city: "Mogilno" },
    { code: "BY1N", city: "Nakło nad Notecią" },
    { code: "BY1S", city: "Świecie" },
    { code: "BY1T", city: "Tuchola" },
    { code: "BY1U", city: "Szubin" },
    { code: "BY1Z", city: "Żnin" },
    { code: "BY2T", city: "Sępólno Krajeńskie" },
    { code: "CIKW", city: "Warszawa" },
    { code: "CZ1C", city: "Częstochowa" },
    { code: "CZ1L", city: "Lubliniec" },
    { code: "CZ1M", city: "Myszków" },
    { code: "CZ1Z", city: "Zawiercie" },
    { code: "CZ2C", city: "Kłobuck" },
    { code: "DIRS", city: "Żż Dirs" },
    { code: "EL1B", city: "Braniewo" },
    { code: "EL1D", city: "Działdowo" },
    { code: "EL1E", city: "Elbląg" },
    { code: "EL1I", city: "Iława" },
    { code: "EL1N", city: "Nowe Miasto Lubawskie" },
    { code: "EL1O", city: "Ostróda" },
    { code: "EL2O", city: "Morąg" },
    { code: "GD1A", city: "Starogard Gdański" },
    { code: "GD1E", city: "Kościerzyna" },
    { code: "GD1G", city: "Gdańsk" },
    { code: "GD1I", city: "Kwidzyn" },
    { code: "GD1M", city: "Malbork" },
    { code: "GD1R", city: "Kartuzy" },
    { code: "GD1S", city: "Sopot" },
    { code: "GD1T", city: "Tczew" },
    { code: "GD1W", city: "Wejherowo" },
    { code: "GD1Y", city: "Gdynia" },
    { code: "GD2I", city: "Sztum" },
    { code: "GD2M", city: "Nowy Dwór Gdański" },
    { code: "GD2W", city: "Puck" },
    { code: "GL1G", city: "Gliwice" },
    { code: "GL1J", city: "Jastrzębie-Zdrój" },
    { code: "GL1R", city: "Racibórz" },
    { code: "GL1S", city: "Ruda Śląska" },
    { code: "GL1T", city: "Tarnowskie Góry" },
    { code: "GL1W", city: "Wodzisław Śląski" },
    { code: "GL1X", city: "Żory" },
    { code: "GL1Y", city: "Rybnik" },
    { code: "GL1Z", city: "Zabrze" },
    { code: "GW1G", city: "Gorzów Wielkopolski" },
    { code: "GW1K", city: "Strzelce Krajeńskie" },
    { code: "GW1M", city: "Międzyrzecz" },
    { code: "GW1S", city: "Słubice" },
    { code: "GW1U", city: "Sulęcin" },
    { code: "JG1B", city: "Bolesławiec" },
    { code: "JG1J", city: "Jelenia Góra" },
    { code: "JG1K", city: "Kamienna Góra" },
    { code: "JG1L", city: "Lubań" },
    { code: "JG1S", city: "Lwówek Śląski" },
    { code: "JG1Z", city: "Zgorzelec" },
    { code: "KA1B", city: "Będzin" },
    { code: "KA1C", city: "Chorzów" },
    { code: "KA1D", city: "Dąbrowa Górnicza" },
    { code: "KA1I", city: "Siemianowice Śląskie" },
    { code: "KA1J", city: "Jaworzno" },
    { code: "KA1K", city: "Katowice" },
    { code: "KA1L", city: "Mysłowice" },
    { code: "KA1M", city: "Mikołów" },
    { code: "KA1P", city: "Pszczyna" },
    { code: "KA1S", city: "Sosnowiec" },
    { code: "KA1T", city: "Tychy" },
    { code: "KA1Y", city: "Bytom" },
    { code: "KI1A", city: "Staszów" },
    { code: "KI1B", city: "Busko-Zdrój" },
    { code: "KI1H", city: "Starachowice" },
    { code: "KI1I", city: "Kazimierza Wielka" },
    { code: "KI1J", city: "Jędrzejów" },
    { code: "KI1K", city: "Końskie" },
    { code: "KI1L", city: "Kielce" },
    { code: "KI1O", city: "Ostrowiec Świętokrzyski" },
    { code: "KI1P", city: "Pińczów" },
    { code: "KI1R", city: "Skarżysko-Kamienna" },
    { code: "KI1S", city: "Sandomierz" },
    { code: "KI1T", city: "Opatów" },
    { code: "KI1W", city: "Włoszczowa" },
    { code: "KN1K", city: "Koło" },
    { code: "KN1N", city: "Konin" },
    { code: "KN1S", city: "Słupca" },
    { code: "KN1T", city: "Turek" },
    { code: "KO1B", city: "Białogard" },
    { code: "KO1D", city: "Drawsko Pomorskie" },
    { code: "KO1E", city: "Sławno" },
    { code: "KO1I", city: "Szczecinek" },
    { code: "KO1K", city: "Koszalin" },
    { code: "KO1L", city: "Kołobrzeg" },
    { code: "KO1W", city: "Wałcz" },
    { code: "KO2B", city: "Świdwin" },
    { code: "KR1B", city: "Sucha Beskidzka" },
    { code: "KR1C", city: "Chrzanów" },
    { code: "KR1E", city: "Oświęcim" },
    { code: "KR1H", city: "Proszowice" },
    { code: "KR1I", city: "Wieliczka" },
    { code: "KR1K", city: "Czernichów" },
    { code: "KR1M", city: "Miechów" },
    { code: "KR1O", city: "Olkusz" },
    { code: "KR1P", city: "Kraków" },
    { code: "KR1S", city: "Słomniki" },
    { code: "KR1W", city: "Wadowice" },
    { code: "KR1Y", city: "Myślenice" },
    { code: "KR2E", city: "Kęty" },
    { code: "KR2I", city: "Niepołomice" },
    { code: "KR2K", city: "Krzeszowice" },
    { code: "KR2P", city: "Skała" },
    { code: "KR2Y", city: "Dobczyce" },
    { code: "KR3I", city: "Skawina" },
    { code: "KS1B", city: "Brzozów" },
    { code: "KS1E", city: "Lesko" },
    { code: "KS1J", city: "Jasło" },
    { code: "KS1K", city: "Krosno" },
    { code: "KS1S", city: "Sanok" },
    { code: "KS2E", city: "Ustrzyki Dolne" },
    { code: "KZ1A", city: "Kalisz" },
    { code: "KZ1E", city: "Kępno" },
    { code: "KZ1J", city: "Jarocin" },
    { code: "KZ1O", city: "Ostrzeszów" },
    { code: "KZ1P", city: "Pleszew" },
    { code: "KZ1R", city: "Krotoszyn" },
    { code: "KZ1W", city: "Ostrów Wielkopolski" },
    { code: "LD1B", city: "Brzeziny" },
    { code: "LD1G", city: "Zgierz" },
    { code: "LD1H", city: "Skierniewice" },
    { code: "LD1K", city: "Kutno" },
    { code: "LD1M", city: "Łódź" },
    { code: "LD1O", city: "Łowicz" },
    { code: "LD1P", city: "Pabianice" },
    { code: "LD1R", city: "Rawa Mazowiecka" },
    { code: "LD1Y", city: "Łęczyca" },
    { code: "LE1G", city: "Głogów" },
    { code: "LE1J", city: "Jawor" },
    { code: "LE1L", city: "Legnica" },
    { code: "LE1U", city: "Lubin" },
    { code: "LE1Z", city: "Złotoryja" },
    { code: "LM1G", city: "Grajewo" },
    { code: "LM1L", city: "Łomża" },
    { code: "LM1W", city: "Wysokie Mazowieckie" },
    { code: "LM1Z", city: "Zambrów" },
    { code: "LU1A", city: "Lubartów" },
    { code: "LU1B", city: "Biała Podlaska" },
    { code: "LU1C", city: "Chełm" },
    { code: "LU1I", city: "Lublin" },
    { code: "LU1K", city: "Kraśnik" },
    { code: "LU1O", city: "Opole Lubelskie" },
    { code: "LU1P", city: "Puławy" },
    { code: "LU1R", city: "Radzyń Podlaski" },
    { code: "LU1S", city: "Świdnik" },
    { code: "LU1U", city: "Łuków" },
    { code: "LU1W", city: "Włodawa" },
    { code: "LU1Y", city: "Ryki" },
    { code: "NS1G", city: "Gorlice" },
    { code: "NS1L", city: "Limanowa" },
    { code: "NS1M", city: "Muszyna" },
    { code: "NS1S", city: "Nowy Sącz" },
    { code: "NS1T", city: "Nowy Targ" },
    { code: "NS1Z", city: "Zakopane" },
    { code: "NS2L", city: "Mszana Dolna" },
    { code: "OL1B", city: "Biskupiec" },
    { code: "OL1C", city: "Olecko" },
    { code: "OL1E", city: "Ełk" },
    { code: "OL1G", city: "Giżycko" },
    { code: "OL1K", city: "Kętrzyn" },
    { code: "OL1L", city: "Lidzbark Warmiński" },
    { code: "OL1M", city: "Mrągowo" },
    { code: "OL1N", city: "Nidzica" },
    { code: "OL1O", city: "Olsztyn" },
    { code: "OL1P", city: "Pisz" },
    { code: "OL1S", city: "Szczytno" },
    { code: "OL1Y", city: "Bartoszyce" },
    { code: "OL2G", city: "Węgorzewo" },
    { code: "OP1B", city: "Brzeg" },
    { code: "OP1G", city: "Głubczyce" },
    { code: "OP1K", city: "Kędzierzyn-Koźle" },
    { code: "OP1L", city: "Olesno" },
    { code: "OP1N", city: "Nysa" },
    { code: "OP1O", city: "Opole" },
    { code: "OP1P", city: "Prudnik" },
    { code: "OP1S", city: "Strzelce Opolskie" },
    { code: "OP1U", city: "Kluczbork" },
    { code: "OS1M", city: "Ostrów Mazowiecka" },
    { code: "OS1O", city: "Ostrołęka" },
    { code: "OS1P", city: "Przasnysz" },
    { code: "OS1U", city: "Pułtusk" },
    { code: "OS1W", city: "Wyszków" },
    { code: "PL1C", city: "Ciechanów" },
    { code: "PL1E", city: "Sierpc" },
    { code: "PL1G", city: "Gostynin" },
    { code: "PL1L", city: "Płońsk" },
    { code: "PL1M", city: "Mława" },
    { code: "PL1O", city: "Sochaczew" },
    { code: "PL1P", city: "Płock" },
    { code: "PL1Z", city: "Żyrardów" },
    { code: "PL2M", city: "Żuromin" },
    { code: "PO1A", city: "Szamotuły" },
    { code: "PO1B", city: "Wągrowiec" },
    { code: "PO1D", city: "Środa Wielkopolska" },
    { code: "PO1E", city: "Wolsztyn" },
    { code: "PO1F", city: "Września" },
    { code: "PO1G", city: "Gniezno" },
    { code: "PO1H", city: "Chodzież" },
    { code: "PO1I", city: "Piła" },
    { code: "PO1K", city: "Kościan" },
    { code: "PO1L", city: "Leszno" },
    { code: "PO1M", city: "Śrem" },
    { code: "PO1N", city: "Nowy Tomyśl" },
    { code: "PO1O", city: "Oborniki" },
    { code: "PO1P", city: "Poznań (V)" },
    { code: "PO1R", city: "Rawicz" },
    { code: "PO1S", city: "Grodzisk Wielkopolski" },
    { code: "PO1T", city: "Trzcianka" },
    { code: "PO1Y", city: "Gostyń" },
    { code: "PO1Z", city: "Złotów" },
    { code: "PO2A", city: "Międzychód" },
    { code: "PO2H", city: "Wyrzysk" },
    { code: "PO2P", city: "Poznań (VI)" },
    { code: "PO2T", city: "Czarnków" },
    { code: "PR1J", city: "Jarosław" },
    { code: "PR1L", city: "Lubaczów" },
    { code: "PR1P", city: "Przemyśl" },
    { code: "PR1R", city: "Przeworsk" },
    { code: "PR2R", city: "Sieniawa" },
    { code: "PT1B", city: "Bełchatów" },
    { code: "PT1O", city: "Opoczno" },
    { code: "PT1P", city: "Piotrków Trybunalski" },
    { code: "PT1R", city: "Radomsko" },
    { code: "PT1T", city: "Tomaszów Mazowiecki" },
    { code: "RA1G", city: "Grójec" },
    { code: "RA1K", city: "Kozienice" },
    { code: "RA1L", city: "Lipsko" },
    { code: "RA1P", city: "Przysucha" },
    { code: "RA1R", city: "Radom" },
    { code: "RA1S", city: "Szydłowiec" },
    { code: "RA1Z", city: "Zwoleń" },
    { code: "RA2G", city: "Białobrzegi" },
    { code: "RA2Z", city: "Pionki" },
    { code: "RZ1A", city: "Łańcut" },
    { code: "RZ1D", city: "Dębica" },
    { code: "RZ1E", city: "Leżajsk" },
    { code: "RZ1R", city: "Ropczyce" },
    { code: "RZ1S", city: "Strzyżów" },
    { code: "RZ1Z", city: "Rzeszów" },
    { code: "RZ2Z", city: "Tyczyn" },
    { code: "SI1G", city: "Garwolin" },
    { code: "SI1M", city: "Mińsk Mazowiecki" },
    { code: "SI1P", city: "Sokołów Podlaski" },
    { code: "SI1S", city: "Siedlce" },
    { code: "SI1W", city: "Węgrów" },
    { code: "SI2S", city: "Łosice" },
    { code: "SL1B", city: "Bytów" },
    { code: "SL1C", city: "Chojnice" },
    { code: "SL1L", city: "Lębork" },
    { code: "SL1M", city: "Miastko" },
    { code: "SL1S", city: "Słupsk" },
    { code: "SL1Z", city: "Człuchów" },
    { code: "SO1C", city: "Czeladź" },
    { code: "SR1L", city: "Łask" },
    { code: "SR1S", city: "Sieradz" },
    { code: "SR1W", city: "Wieluń" },
    { code: "SR1Z", city: "Zduńska Wola" },
    { code: "SR2L", city: "Poddębice" },
    { code: "SR2W", city: "Pajęczno" },
    { code: "SU1A", city: "Augustów" },
    { code: "SU1N", city: "Sejny" },
    { code: "SU1S", city: "Suwałki" },
    { code: "SW1D", city: "Dzierżoniów" },
    { code: "SW1K", city: "Kłodzko" },
    { code: "SW1S", city: "Świdnica" },
    { code: "SW1W", city: "Wałbrzych" },
    { code: "SW1Z", city: "Ząbkowice Śląskie" },
    { code: "SW2K", city: "Nowa Ruda" },
    { code: "SZ1C", city: "Choszczno" },
    { code: "SZ1G", city: "Gryfice" },
    { code: "SZ1K", city: "Kamień Pomorski" },
    { code: "SZ1L", city: "Łobez" },
    { code: "SZ1M", city: "Myślibórz" },
    { code: "SZ1O", city: "Goleniów" },
    { code: "SZ1S", city: "Szczecin" },
    { code: "SZ1T", city: "Stargard" },
    { code: "SZ1W", city: "Świnoujście" },
    { code: "SZ1Y", city: "Gryfino" },
    { code: "SZ2S", city: "Police" },
    { code: "SZ2T", city: "Pyrzyce" },
    { code: "TB1K", city: "Kolbuszowa" },
    { code: "TB1M", city: "Mielec" },
    { code: "TB1N", city: "Nisko" },
    { code: "TB1S", city: "Stalowa Wola" },
    { code: "TB1T", city: "Tarnobrzeg" },
    { code: "TO1B", city: "Brodnica" },
    { code: "TO1C", city: "Chełmno" },
    { code: "TO1G", city: "Golub-Dobrzyń" },
    { code: "TO1T", city: "Toruń" },
    { code: "TO1U", city: "Grudziądz" },
    { code: "TO1W", city: "Wąbrzeźno" },
    { code: "TR1B", city: "Brzesko" },
    { code: "TR1D", city: "Dąbrowa Tarnowska" },
    { code: "TR1O", city: "Bochnia" },
    { code: "TR1T", city: "Tarnów" },
    { code: "TR2T", city: "Tuchów" },
    { code: "WA1G", city: "Grodzisk Mazowiecki" },
    { code: "WA1I", city: "Piaseczno" },
    { code: "WA1L", city: "Legionowo" },
    { code: "WA1M", city: "Warszawa (VI)" },
    { code: "WA1N", city: "Nowy Dwór Mazowiecki" },
    { code: "WA1O", city: "Otwock" },
    { code: "WA1P", city: "Pruszków" },
    { code: "WA1W", city: "Wołomin" },
    { code: "WA2M", city: "Warszawa (VII)" },
    { code: "WA3M", city: "Warszawa (IX)" },
    { code: "WA4M", city: "Warszawa (X)" },
    { code: "WA5M", city: "Warszawa (XIII)" },
    { code: "WA6M", city: "Warszawa (XV)" },
    { code: "WL1A", city: "Aleksandrów Kujawski" },
    { code: "WL1L", city: "Lipno" },
    { code: "WL1R", city: "Radziejów" },
    { code: "WL1W", city: "Włocławek" },
    { code: "WL1Y", city: "Rypin" },
    { code: "WR1E", city: "Oleśnica" },
    { code: "WR1K", city: "Wrocław" },
    { code: "WR1L", city: "Wołów" },
    { code: "WR1M", city: "Milicz" },
    { code: "WR1O", city: "Oława" },
    { code: "WR1S", city: "Środa Śląska" },
    { code: "WR1T", city: "Strzelin" },
    { code: "WR1W", city: "Trzebnica" },
    { code: "ZA1B", city: "Biłgoraj" },
    { code: "ZA1H", city: "Hrubieszów" },
    { code: "ZA1J", city: "Janów Lubelski" },
    { code: "ZA1K", city: "Krasnystaw" },
    { code: "ZA1T", city: "Tomaszów Lubelski" },
    { code: "ZA1Z", city: "Zamość" },
    { code: "ZG1E", city: "Zielona Góra" },
    { code: "ZG1G", city: "Żagań" },
    { code: "ZG1K", city: "Krosno Odrzańskie" },
    { code: "ZG1N", city: "Nowa Sól" },
    { code: "ZG1R", city: "Żary" },
    { code: "ZG1S", city: "Świebodzin" },
    { code: "ZG1W", city: "Wschowa" },
    { code: "ZG2K", city: "Gubin" },
    { code: "ZG2S", city: "Sulechów" }
];